<?php
/**
 * EaDesgin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@eadesign.ro so we can send you a copy immediately.
 *
 * @category    eadesigndev_pdfgenerator
 * @copyright   Copyright (c) 2008-2016 EaDesign by Eco Active S.R.L.
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>

<p class="main-description detailtext">
    We are a company specialized in development for Magento from Iasi Romania. We develop extensions for our clients and
    for the community. We are very passionate programmers, both for backend and frontend.
    We design better tools to improve your services and help you communicate more efficiently with your clients.
</p>

<div class="available" style="text-align: center; font-family: 'Oswald', sans-serif; font-size: 40px; padding: 20px 0">
    ARE YOU READY? </br>
    WE'RE AVAILABLE!</br>
    Let's talk!</br>
</div>

<p class="before-end detailtext">
    The first and most important step is to get to know each other. Once we are well acquainted with your area of
    expertise, work ethics and strategies as well as with your competition, together with you, we will start to
    elaborate a the most efficient work plan as possible. The analysis of your professional domain is a demanding but
    necessary process if we want to ensure that your online store will be ahead of your competition while maintaining
    and integrating your brand identity into your new web-store.
</p>
<p class="bugs detailtext">
    If you have any bug or problem with our extension do not hesitate to contact us. We ha a dedicated email for you to
    use in this cases, <a href="mailto:m2dev@eadesign.ro">Support and bug email, m2dev@eadesign.ro</a>
    . <strong style="color: #f26422;"> You can use the same email address <a href="mailto:m2dev@eadesign.ro">m2dev@eadesign.ro</a> if you need custom
    magento development and programming. </strong> Or you can contact us from our site, <a href="https://www.eadesign.ro"
                                                                                 target="_blank">https://www.eadesign.ro</a>
    Sending us feedback helps us get better and create more reliable tools for you and for the Magento community.
</p>
<p></p>
<p>
    <iframe width="100%" height="515" src="https://www.youtube.com/embed/hdSmq4WIuV4" frameborder="0"
            allowfullscreen></iframe>
</p>