<?php
/**
 * EaDesgin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@eadesign.ro so we can send you a copy immediately.
 *
 * @category    eadesigndev_pdfgenerator
 * @copyright   Copyright (c) 2008-2016 EaDesign by Eco Active S.R.L.
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>

<h3 class="title-details">Company standards</h3>
<p class="before-end detailtext">
    We are passionate about technology, always looking to innovate and provide quality services for our clients. We
    like to keep things simple, understandable and executable. We encourage our team to pursue their passions, listen to
    one another, and never stop learning. We also encourage them to work hard, play hard, and rest hard. Work is only
    one side of your personal life, and we try to keep it that way.
</p>
<p class="detailtext">Customize your Magento© Platform with our extensions or let us customize it for you. Ask us anything, for our goal is
    to help you create the store that will make you come out ahead of your competition and help your clients as
    well!
    <a href="https://www.eadesign.ro/shop" target="_blank">
        Contact Us!
    </a>
</p>
<p class="iframe">
    <iframe width="950" height="611" src="https://www.youtube.com/embed/wzaGJHOAgF8"
            frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
</p>